window.SITE={wa:'6281229871936',phone:'0812-2987-1936',shopee:'https://shopee.co.id/siswantogroup',tokopedia:'https://www.tokopedia.com/rambak-kulit-siswanto',maps:'https://www.google.com/maps/search/?api=1&query=Dusun+III+Gumpang+Kartasura+Sukoharjo+57169',address:'Dusun III, Gumpang, Kartasura, Sukoharjo Regency, Central Java 57169',heroImg:'assets/visual-500.svg'};
window.PRODUCTS=[
{id:'r500',name:'Rambak Kulit Sapi 500g',cat:'rambak',pack:'500g',img:'assets/visual-500.svg',buyer:'Keluarga, oleh-oleh, dan pembelian online',desc:'Kemasan besar Rambak Kulit Sapi Siswanto untuk kebutuhan camilan, oleh-oleh, dan persediaan rumah.',high:['Kanal pembelian ke Shopee','WhatsApp untuk konfirmasi jumlah besar','Harga mengikuti marketplace'],note:'Harga dan ketersediaan mengikuti kanal marketplace resmi.'},
{id:'r200',name:'Rambak Kulit Sapi 200g',cat:'rambak',pack:'200g',img:'assets/visual-200.svg',buyer:'Keluarga, oleh-oleh, pembelian online',desc:'Varian rambak kulit sapi untuk konsumsi harian dan oleh-oleh.',high:['Showcase katalog','Arah pembelian ke marketplace','Tidak checkout di website'],note:'Stok dan harga mengikuti kanal marketplace.'},
{id:'r250',name:'Rambak Kulit Sapi 250g',cat:'rambak',pack:'250g',img:'assets/visual-200.svg',buyer:'Customer retail dan reseller kecil',desc:'Kemasan menengah untuk kebutuhan camilan, persediaan rumah, dan repeat order.',high:['Cocok untuk repeat order','Shopee/Tokopedia directed','WhatsApp untuk pertanyaan'],note:'Konfirmasi varian melalui marketplace atau WhatsApp.'},
{id:'tongkol',name:'Kerupuk Ikan Tongkol 1kg',cat:'kerupuk',pack:'1kg',img:'assets/visual-tongkol.svg',buyer:'Rumah tangga, reseller, toko',desc:'Produk kerupuk ikan tongkol kemasan besar untuk kebutuhan persediaan dan penjualan ulang.',high:['Showcase varian produk','Cocok untuk pembelian besar','CTA marketplace'],note:'Foto dan link produk spesifik dapat ditambahkan belakangan.'},
{id:'tahu',name:'Kerupuk Tahu/Kotak 1kg',cat:'kerupuk',pack:'1kg',img:'assets/visual-tongkol.svg',buyer:'Toko, reseller, kebutuhan stok',desc:'Varian kerupuk kemasan 1kg untuk kebutuhan toko, reseller, dan pemesanan rutin.',high:['Katalog grosir','Marketplace directed','Tidak simpan data pembeli'],note:'Gunakan WhatsApp untuk kebutuhan jumlah besar.'},
{id:'krecek',name:'Krecek / Rambak Sayur',cat:'krecek',pack:'Sesuai ketersediaan',img:'assets/visual-500.svg',buyer:'Rumah makan dan kebutuhan masak',desc:'Produk untuk kebutuhan olahan masakan dan pembelian terencana.',high:['Cocok B2B','Konfirmasi ketersediaan','WA owner'],note:'Untuk kebutuhan rutin, hubungi owner via WhatsApp.'},
{id:'grosir',name:'Pemesanan Grosir / Event',cat:'grosir',pack:'By request',img:'assets/visual-workshop.svg',buyer:'Reseller, event, toko, rumah makan',desc:'Jalur komunikasi untuk kerja sama, reseller, event, atau kebutuhan pembelian besar.',high:['Langsung ke owner','Tidak ada database','Aman dan cepat'],note:'Form hanya menyusun pesan WhatsApp, tidak menyimpan data.'}
];
