window.SITE={wa:'6281229871936',phone:'0812-2987-1936',shopee:'https://id.shp.ee/ZLWzM41K',tokopedia:'https://tk.tokopedia.com/ZSCdfFMqc/',maps:'https://www.google.com/maps/search/?api=1&query=Dusun+III+Gumpang+Kartasura+Sukoharjo+57169',address:'Dusun III, Gumpang, Kartasura, Sukoharjo Regency, Central Java 57169'};
window.PRODUCTS=[
{id:'r200',name:'Rambak Kulit Sapi 200g',cat:'rambak',pack:'200g',buyer:'Keluarga, oleh-oleh, pembelian online',desc:'Produk rambak kulit sapi untuk kebutuhan konsumsi harian dan oleh-oleh.',high:['Showcase katalog','Arah pembelian ke marketplace','Foto final akan diganti'],note:'Stok dan harga mengikuti kanal marketplace.'},
{id:'r250',name:'Rambak Kulit Sapi 250g',cat:'rambak',pack:'250g',buyer:'Customer retail dan reseller kecil',desc:'Varian kemasan lebih besar untuk kebutuhan camilan dan persediaan rumah.',high:['Cocok untuk repeat order','Bisa diarahkan ke Shopee/Tokopedia','Tidak checkout di website'],note:'Konfirmasi varian melalui marketplace atau WhatsApp.'},
{id:'tongkol',name:'Kerupuk Ikan Tongkol 1kg',cat:'kerupuk',pack:'1kg',buyer:'Rumah tangga, reseller, toko',desc:'Produk kerupuk kemasan besar yang ditampilkan sebagai bagian katalog.',high:['Showcase varian produk','Cocok untuk pembelian besar','CTA marketplace'],note:'Foto dan link produk spesifik dapat ditambahkan belakangan.'},
{id:'tahu',name:'Kerupuk Tahu/Kotak 1kg',cat:'kerupuk',pack:'1kg',buyer:'Toko, reseller, kebutuhan stok',desc:'Varian kerupuk 1kg untuk kebutuhan persediaan dan penjualan ulang.',high:['Katalog grosir','Marketplace directed','Tidak simpan data pembeli'],note:'Gunakan WhatsApp untuk kebutuhan jumlah besar.'},
{id:'krecek',name:'Krecek / Rambak Sayur',cat:'krecek',pack:'Sesuai ketersediaan',buyer:'Rumah makan dan kebutuhan masak',desc:'Produk untuk kebutuhan olahan masakan dan pembelian terencana.',high:['Cocok B2B','Konfirmasi ketersediaan','WA owner'],note:'Untuk kebutuhan rutin, hubungi owner via WhatsApp.'},
{id:'grosir',name:'Pemesanan Grosir / Event',cat:'grosir',pack:'By request',buyer:'Reseller, event, toko, rumah makan',desc:'Jalur komunikasi untuk kerja sama atau kebutuhan pembelian besar.',high:['Langsung ke owner','Tidak ada database','Aman dan cepat'],note:'Form hanya menyusun pesan WhatsApp, tidak menyimpan data.'}
];
